INSERT INTO desserts (name, description, price, image_url, created_at) VALUES
('Brownie', 'Brownie de chocolate com nozes', 12.00, '/img/desserts/brownie.jpg', NOW()),
('Cheesecake', 'Cheesecake com frutas vermelhas', 15.00, '/img/desserts/cheesecake.jpg', NOW()),
('Petit Gâteau', 'Bolo quente com sorvete', 18.00, '/img/desserts/petit-gateau.jpg', NOW()),
('Tiramisu', 'Doce italiano com café e cacau', 16.00, '/img/desserts/tiramisu.jpg', NOW()),
('Mousse de Maracujá', 'Mousse leve e refrescante', 10.00, '/img/desserts/mousse-maracuja.jpg', NOW()),
('Pudim', 'Pudim de leite tradicional', 11.00, '/img/desserts/pudim.jpg', NOW()),
('Sorvete de Chocolate', 'Bola de sorvete de chocolate', 9.00, '/img/desserts/sorvete-chocolate.jpg', NOW()),
('Sorvete de Morango', 'Bola de sorvete de morango', 9.00, '/img/desserts/sorvete-morango.jpg', NOW()),
('Banoffee', 'Torta de banana com doce de leite e chantilly', 14.00, '/img/desserts/banoffee.jpg', NOW()),
('Torta de Limão', 'Massa crocante com creme de limão', 13.00, '/img/desserts/torta-limao.jpg', NOW()),
('Brigadeiro', 'Doce de chocolate enrolado', 4.00, '/img/desserts/brigadeiro.jpg', NOW()),
('Beijinho', 'Doce de coco com leite condensado', 4.00, '/img/desserts/beijinho.jpg', NOW()),
('Palha Italiana', 'Chocolate com biscoito', 7.00, '/img/desserts/palha-italiana.jpg', NOW()),
('Creme de Papaya', 'Papaia com licor de cassis', 12.00, '/img/desserts/papaya.jpg', NOW()),
('Rocambole de Doce de Leite', 'Bolo recheado enrolado', 13.00, '/img/desserts/rocambole.jpg', NOW());
